apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: eks
  title: EKS Cluster
  description: Create an EKS Cluster to host workloads
  tags:
    - caas
    - eks
spec:
  owner: infrastructure
  type: service
  parameters:
    - title: Provide some simple information
      required:
        - cluster_id
        - owner
      properties:
        cluster_id:
          title: Name
          type: string
          description: Unique name of the component
          ui:field: EntityNamePicker
        owner:
          title: Owner
          type: string
          description: Owner of the component
          ui:field: OwnerPicker
          ui:options:
            allowedKinds:
              - Group
    - title: Destination
      required:
        - repo_url
      properties:
        repo_url:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
        pr_branchname:
          title: Branch name for Pull Request
          type: string
  steps:
    - id: template
      name: Fetch Cluster claim template
      action: fetch:template
      input:
        url: ./skeleton
        targetPath: demo/clusters/
        values:
          cluster_id: ${{ parameters.cluster_id }}
    - id: publish
      name: Publish
      action: publish:github:pull-request
      input:
        allowedHosts: ['github.com']
        title: EKS Request
        descripton: New cluster, please
        repoUrl: ${{ parameters.repo_url }} 
        branchName: eks-claim
  output:
    text:
      - title: Accept Pull Request
        content: |
          To finish publishing the cluster, accept the [pull request](${{ steps['publish'].output.remoteUrl }}) 