apiVersion: aws.caas.upbound.io/v1alpha1
kind: Cluster
metadata:
  name: ${{ values.cluster_id }}
  namespace: default
spec:
  parameters:
    id: ${{ values.cluster_id }}
    region: eu-west-1
    version: "1.28"
    nodes:
      count: 3
      size: small
  writeConnectionSecretToRef:
    name: ${{ values.cluster_id }}-kubeconfig