apiVersion: backstack.cncf.io/v1alpha1
kind: AKSCluster
metadata:
  name: backstack-vault
  namespace: default
spec:
  parameters:
    id: backstack-vault
    region: West Europe
    version: 1.27.3
    nodes:
      count: 3
      instanceType: Standard_B2s
  writeConnectionSecretToRef:
    name: backstack-vault-kubeconfig