apiVersion: backstack.cncf.io/v1alpha1
kind: AKSCluster
metadata:
  name: kubecon
  namespace: default
spec:
  parameters:
    id: kubecon
    region: North Europe
    version: 1.27.3
    nodes:
      count: 3
      instanceType: Standard_B2s
  writeConnectionSecretToRef:
    name: kubecon-kubeconfig